linters:
  disable-all: true
  enable:
  - ineffassign
  - goimports
  - govet
  - misspell
  - revive
  - unused
  - goconst
  - forbidigo
  - predeclared
linters-settings:
  revive:
    rules:
    - name: confusing-naming
      disabled: true
    - name: exported
      disabled: false
  goconst: 
    min-len: 2
    min-occurrences: 10
    match-constant: true
    ignore-strings: "metadata.+"
  forbidigo:
    forbid:
      - p: ^*\.Sleep.*$
        msg: "No sleeps please use the appropriate polls and watch"
      - p: ^fmt\.Print.*$
        msg: "No format prints, please testing or logrus packages"
run:
  tests: true
  relative-path-mode: wd
  build-tags: [validation,"2.10"]
  timeout: 8m
issues:
  max-issues-per-linter: 0
  exclude-files:
    - ^*\.yaml$
    - ^*\.yml$