#!/bin/bash

# Test script to verify inventory file path fixes
echo "=== Testing Inventory File Path Fixes ==="

# Create test directory structure
mkdir -p /tmp/test_airgap/root/ansible/rke2/airgap/inventory/
mkdir -p /tmp/test_airgap/root/go/src/github.com/rancher/qa-infra-automation/ansible/rke2/airgap/inventory/

# Create a test inventory file at the Terraform source location
cat > /tmp/test_airgap/root/go/src/github.com/rancher/qa-infra-automation/ansible/rke2/airgap/inventory/inventory.yml << 'EOF'
---
all:
  hosts:
    server1:
      ansible_host: 192.168.1.10
    server2:
      ansible_host: 192.168.1.11
    server3:
      ansible_host: 192.168.1.12
  children:
    rke2_servers:
      hosts:
        server1:
        server2:
        server3:
EOF

# Test the airgap_apply_infrastructure.sh logic
echo "=== Testing airgap_apply_infrastructure.sh logic ==="
cd /tmp/test_airgap/root

# Simulate the inventory file copying logic from airgap_apply_infrastructure.sh
SOURCE_INVENTORY="/root/go/src/github.com/rancher/qa-infra-automation/ansible/rke2/airgap/inventory/inventory.yml"
SHARED_VOLUME_INVENTORY="/root/ansible-inventory.yml"
ANSIBLE_EXPECTED_INVENTORY="/root/ansible/rke2/airgap/inventory.yml"

if [ -f "$SOURCE_INVENTORY" ] && [ -s "$SOURCE_INVENTORY" ]; then
    echo 'SUCCESS: inventory.yml generated by terraform apply exists and has content'
    
    # Copy to shared volume location (for artifact extraction)
    cp "$SOURCE_INVENTORY" "$SHARED_VOLUME_INVENTORY"
    echo "Inventory file copied to shared volume location: $SHARED_VOLUME_INVENTORY"
    
    # Copy to Ansible expected location (for Ansible playbook execution)
    mkdir -p /root/ansible/rke2/airgap/inventory/
    cp "$SOURCE_INVENTORY" "$ANSIBLE_EXPECTED_INVENTORY"
    echo "Inventory file copied to Ansible expected location: $ANSIBLE_EXPECTED_INVENTORY"
    
    # Show inventory file contents for debugging
    echo '=== Inventory File Contents ==='
    cat "$ANSIBLE_EXPECTED_INVENTORY"
    echo '=== End Inventory File Contents ==='
else
    echo 'WARNING: inventory.yml not found or empty after apply'
fi

# Test the Ansible script logic
echo ""
echo "=== Testing Ansible script logic ==="

# Simulate the inventory file validation logic from Ansible scripts
mkdir -p /root/ansible/rke2/airgap/inventory/

# Check if inventory file exists at the expected Terraform location
if [[ ! -f "/root/ansible/rke2/airgap/inventory.yml" ]]; then
    echo "Ansible inventory file not found at /root/ansible/rke2/airgap/inventory.yml"
    
    # Check if inventory file exists in the shared volume (legacy location)
    if [[ -f "/root/ansible-inventory.yml" ]]; then
        echo "Found inventory file at shared volume location, copying to expected location..."
        cp /root/ansible-inventory.yml /root/ansible/rke2/airgap/inventory.yml
        echo "Inventory file copied successfully"
    else
        echo "ERROR: Ansible inventory file not found at either:"
        echo "  - /root/ansible/rke2/airgap/inventory.yml (Terraform location)"
        echo "  - /root/ansible-inventory.yml (Shared volume location)"
        exit 1
    fi
fi

# Verify final result
echo ""
echo "=== Verification ==="
if [[ -f "/root/ansible/rke2/airgap/inventory.yml" ]]; then
    echo "✅ SUCCESS: Inventory file found at expected Ansible location"
    echo "File contents:"
    cat /root/ansible/rke2/airgap/inventory.yml
else
    echo "❌ FAILED: Inventory file not found at expected Ansible location"
    exit 1
fi

# Cleanup
rm -rf /tmp/test_airgap

echo "=== Test Completed Successfully ==="