---
name: Report Results to Qase
description: "Builds v2 reporter and reports to Qase"
inputs:
  hb-qase-test-run-id:
    description: "Hostbusters Qase Test Run ID"
    required: true
  qase-automation-token:
    description: "Qase Automation Token"
    required: true
  hb-qase-project-id:
    description: "Hostbusters Qase Project ID"
    required: true
runs:
  using: composite
  steps:
    - run: |
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }}; \
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }}; \
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }}; \
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh; /home/runner/work/tests/tests/reporter
      shell: bash
