---
name: Run Daily Provisioning Test Suites
description: "Runs daily provisioning test suites"

inputs:
  reporting:
    description: "Enable reporting"
    required: false
    default: "false"
  tags:
    description: "Test tags to run (comma-separated)"
    required: false
    default: "recurring"

runs:
  using: composite
  steps:
    - name: Run K3S Provisioning Tests
      id: k3s
      shell: bash
      continue-on-error: true
      run: |
        set +e

        gotestsum --format standard-verbose \
          --packages=github.com/rancher/tests/validation/provisioning/k3s \
          --junitfile results_k3s.xml \
          --jsonfile results_k3s.json \
          -- -timeout=3h -tags=${{ inputs.tags }} -v

        k3s_exit=$?
        echo "k3s_exit=$k3s_exit" >> "$GITHUB_ENV"
        cp results_k3s.json results.json

        if [[ "${{ inputs.reporting }}" == "true" ]]; then
          ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
          ./validation/reporter
        fi

    - name: Run RKE2 Provisioning Tests
      id: rke2
      shell: bash
      continue-on-error: true
      run: |
        set +e

        gotestsum --format standard-verbose \
          --packages=github.com/rancher/tests/validation/provisioning/rke2 \
          --junitfile results_rke2.xml \
          --jsonfile results_rke2.json \
          -- -timeout=3h -tags=${{ inputs.tags }} -v

        rke2_exit=$?
        echo "rke2_exit=$rke2_exit" >> "$GITHUB_ENV"
        cp results_rke2.json results.json

        if [[ "${{ inputs.reporting }}" == "true" ]]; then
          ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
          ./validation/reporter
        fi

    - name: Run Dualstack Provisioning Tests
      id: dualstack
      shell: bash
      continue-on-error: true
      run: |
        set +e

        gotestsum --format standard-verbose \
          --packages=github.com/rancher/tests/validation/provisioning/dualstack \
          --junitfile results_dualstack.xml \
          --jsonfile results_dualstack.json \
          -- -timeout=3h -tags=${{ inputs.tags }} -v

        dualstack_exit=$?
        echo "dualstack_exit=$dualstack_exit" >> "$GITHUB_ENV"
        cp results_dualstack.json results.json

        if [[ "${{ inputs.reporting }}" == "true" ]]; then
          ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
          ./validation/reporter
        fi

    - name: Run IPv6 Provisioning Tests
      id: ipv6
      shell: bash
      continue-on-error: true
      run: |
        set +e

        gotestsum --format standard-verbose \
          --packages=github.com/rancher/tests/validation/provisioning/ipv6 \
          --junitfile results_ipv6.xml \
          --jsonfile results_ipv6.json \
          -- -timeout=3h -tags=${{ inputs.tags }} -v

        ipv6_exit=$?
        echo "ipv6_exit=$ipv6_exit" >> "$GITHUB_ENV"
        cp results_ipv6.json results.json

        if [[ "${{ inputs.reporting }}" == "true" ]]; then
          ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
          ./validation/reporter
        fi

    - name: Show failed tests
      run: |
        failed=0
        if [ "$k3s_exit" -ne 0 ]; then
          echo "Failed K3S tests:"
          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_k3s.json
          failed=1
        fi

        if [ "$rke2_exit" -ne 0 ]; then
          echo "Failed RKE2 tests:"
          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_rke2.json
          failed=1
        fi

        if [ "$dualstack_exit" -ne 0 ]; then
          echo "Failed Dualstack tests:"
          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_dualstack.json
          failed=1
        fi

        if [ "$ipv6_exit" -ne 0 ]; then
          echo "Failed IPv6 tests:"
          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_ipv6.json
          failed=1
        fi

        if [ "$failed" -eq 1 ]; then
          exit 1
        fi
      shell: bash
