---
name: "Set Rancher Chart URL"
description: "Sets the Rancher url depending on the provided Rancher repo for Prime builds only"
inputs:
  rancher-repo:
    description: "The rancher repo"
    required: true
  staging-chart-url:
    description: "The chart url to use if the repo is latest or alpha"
    required: true
  fallback-chart-url:
    description: "The fallback chart url if the repo is not latest or alpha"
    default: ""
  env-var-name:
    description: "The name of the environment variable to set"
    default: "RANCHER_HELM_CHART_URL"
outputs:
  chart_url:
    description: "The determined chart url"
    value: ${{ steps.determine-chart-url.outputs.chart_url }}
runs:
  using: "composite"
  steps:
    - name: Determine chart url
      id: determine-chart-url
      shell: bash
      run: |
        RANCHER_REPO="${{ inputs.rancher-repo }}"

        if [[ "$RANCHER_REPO" == "latest" ]] || [[ "$RANCHER_REPO" == "alpha" ]]; then
          CHART_URL="${{ inputs.staging-chart-url }}"
        else
          CHART_URL="${{ inputs.fallback-chart-url }}"
        fi
        
        echo "chart_url=$CHART_URL" >> $GITHUB_OUTPUT
    
    - name: Set environment variable
      uses: ./.github/actions/set-env-var
      with:
        key: ${{ inputs.env-var-name }}
        value: ${{ steps.determine-chart-url.outputs.chart_url }}
