---
 name: Run Dualstack Test Suite
 description: "Runs a specific test suite based on input"
 inputs:
   suite:
     description: "The test suite to run"
     required: true
 runs:
   using: composite
   steps:
     - name: Run Selected Test Suite
       id: run-tests
       run: |
         set +e
         case "${{ inputs.suite }}" in
           rancher-server-one)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/certificates/dualstack \
               --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestCertRotationDualstackTestSuite/TestCertRotationDualstack";
             cert_exit=$?;
             echo "cert_exit=$cert_exit" >> $GITHUB_ENV;
             ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
             ./validation/reporter

             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/deleting/dualstack \
               --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestDeleteDualstackClusterTestSuite/TestDeletingDualstackCluster";
             delete_exit=$?;
             echo "delete_exit=$delete_exit" >> $GITHUB_ENV;
             ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
             ./validation/reporter

             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/dualstack \
               --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestNodeScalingDualstackTestSuite/TestScalingDualstackNodePools";
             node_scale_exit=$?;
             echo "node_scale_exit=$node_scale_exit" >> $GITHUB_ENV;
             ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
             ./validation/reporter
             ;;
           rancher-server-two)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/dualstack \
               --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v;
             prov_exit=$?;
             echo "prov_exit=$prov_exit" >> $GITHUB_ENV;
             ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
             ./validation/reporter

             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/dualstack \
               --junitfile resultst.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestSnapshotDualstackRestoreTestSuite/TestSnapshotDualstackRestore";
             snap_restore_exit=$?;
             echo "snap_restore_exit=$snap_restore_exit" >> $GITHUB_ENV;
             ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
             ./validation/reporter

             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/upgrade/dualstack \
               --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestUpgradeDualstackKubernetesTestSuite/TestUpgradeDualstackKubernetes";
             upgrade_exit=$?;
             echo "upgrade_exit=$upgrade_exit" >> $GITHUB_ENV;
             ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
             ./validation/reporter
             ;;
         esac
       shell: bash
       continue-on-error: true

     - name: Show failed tests
       run: |
         declare -A suites=(
           [cert_exit]="Cert Rotation"
           [delete_exit]="Delete Cluster"
           [node_scale_exit]="Node Scaling"
           [prov_exit]="Provisioning"
           [snap_restore_exit]="Snapshot Restore"
           [upgrade_exit]="Kubernetes Upgrade"
         )

         for exit_code in "${!suites[@]}"; do
           exit_val="${!exit_code}"

           if [ "$exit_val" != "" ] && [ "$exit_val" -ne 0 ]; then
             echo "Failed ${suites[$exit_code]} tests:"
             jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results.json
             echo ""
             exit 1
           fi
         done
       shell: bash