---
name: Run Test Suites
description: "Runs various test suites"
inputs:
  hb-qase-test-run-id:
    description: "Hostbusters Qase Test Run ID"
    required: true
  qase-automation-token:
    description: "Qase Automation Token"
    required: true
  hb-qase-project-id:
    description: "Hostbusters Qase Project ID"
    required: true
runs:
  using: composite
  steps:
    - name: Run Certificate Rotation Test Suite
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/certificates/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestCertRotationTestSuite/TestCertRotation";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true
    
    - name: Run Delete Cluster Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/deleting/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestDeleteClusterTestSuite/TestDeletingCluster";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Delete Init Machine Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/deleting/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestDeleteInitMachineTestSuite/TestDeleteInitMachine";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Node Replacing Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestNodeReplacingTestSuite/TestReplacingNodes";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run K3S Provisioning Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/k3s \
        --junitfile results.xml -- -timeout=3h -tags=recurring -v;
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run RKE2 Provisioning Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/rke2 \
        --junitfile results.xml -- -timeout=3h -tags=recurring -v;
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Scaling Custom Cluster Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestCustomClusterNodeScalingTestSuite/TestScalingCustomClusterNodes";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Scaling Node Driver Cluster Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestNodeScalingTestSuite/TestScalingNodePools";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Snapshot Recurring Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestSnapshotRecurringTestSuite/TestSnapshotRecurringRestores";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Snapshot Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestSnapshotRestoreTestSuite/TestSnapshotRestore";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Snapshot Windows Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestSnapshotRestoreWindowsTestSuite/TestSnapshotRestoreWindows";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Upgrade Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/upgrade/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestKubernetesUpgradeTestSuite/TestUpgradeKubernetes";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Upgrade Windows Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/upgrade/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestWindowsKubernetesUpgradeTestSuite/TestUpgradeWindowsKubernetes";
        export QASE_TEST_RUN_ID=${{ inputs.hb-qase-test-run-id }};
        export QASE_AUTOMATION_TOKEN=${{ inputs.qase-automation-token }};
        export QASE_PROJECT_ID=${{ inputs.hb-qase-project-id }};
        /home/runner/work/tests/tests/validation/pipeline/scripts/build_qase_reporter_v2.sh;
        /home/runner/work/tests/tests/validation/reporter
      shell: bash
      continue-on-error: true