---
 name: Run Test Suite
 description: "Runs a specific test suite based on input"
 inputs:
   suite:
     description: "The test suite to run"
     required: true
 runs:
   using: composite
   steps:
     - name: Run Selected Test Suite
       run: |
         set +e
         case "${{ inputs.suite }}" in
           cert-rotation)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/certificates/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestCertRotationTestSuite/TestCertRotation";;
           delete-cluster)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/deleting/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestDeleteClusterTestSuite/TestDeletingCluster";;
           delete-init-machine)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/deleting/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestDeleteInitMachineTestSuite/TestDeleteInitMachine";;
           node-replacing)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestNodeReplacingTestSuite/TestReplacingNodes";;
           scaling-custom-cluster)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestCustomClusterNodeScalingTestSuite/TestScalingCustomClusterNodes";;
           scaling-node-driver)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestNodeScalingTestSuite/TestScalingNodePools";;
           k3s-provisioning)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v;;
           rke2-provisioning)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/rke2 \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v;;
           snapshot)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestSnapshotRestoreTestSuite/TestSnapshotRestore";;
           snapshot-windows)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestSnapshotRestoreWindowsTestSuite/TestSnapshotRestoreWindows";;
           snapshot-recurring)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestSnapshotRecurringTestSuite/TestSnapshotRecurringRestores";;
           upgrade)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/upgrade/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestKubernetesUpgradeTestSuite/TestUpgradeKubernetes";;
           upgrade-windows)
             gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/upgrade/rke2k3s \
             --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v -run "TestWindowsKubernetesUpgradeTestSuite/TestUpgradeWindowsKubernetes";;
         esac

         ./validation/pipeline/scripts/build_qase_reporter_v2.sh
         ./validation/reporter
       shell: bash
       continue-on-error: true