---
name: Run Test Suites
description: "Runs various test suites"
runs:
  using: composite
  steps:
    - name: Run Certificate Rotation Test Suite
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/certificates/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestCertRotationTestSuite/TestCertRotation";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true
    
    - name: Run Delete Cluster Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/deleting/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestDeleteClusterTestSuite/TestDeletingCluster";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Delete Init Machine Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/deleting/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestDeleteInitMachineTestSuite/TestDeleteInitMachine";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Node Replacing Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestNodeReplacingTestSuite/TestReplacingNodes";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run K3S Provisioning Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/k3s \
        --junitfile results.xml -- -timeout=3h -tags=recurring -v;
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run RKE2 Provisioning Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/rke2 \
        --junitfile results.xml -- -timeout=3h -tags=recurring -v;
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Scaling Custom Cluster Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestCustomClusterNodeScalingTestSuite/TestScalingCustomClusterNodes";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Scaling Node Driver Cluster Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/nodescaling/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestNodeScalingTestSuite/TestScalingNodePools";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Snapshot Recurring Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestSnapshotRecurringTestSuite/TestSnapshotRecurringRestores";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Snapshot Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestSnapshotRestoreTestSuite/TestSnapshotRestore";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Snapshot Windows Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/snapshot/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestSnapshotRestoreWindowsTestSuite/TestSnapshotRestoreWindows";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Upgrade Tests
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/upgrade/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestKubernetesUpgradeTestSuite/TestUpgradeKubernetes";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run Upgrade Windows Tests
      env:
        QASE_TEST_RUN_ID: ${{ inputs.hb-qase-test-run-id }}
        QASE_AUTOMATION_TOKEN: ${{ inputs.qase-automation-token }}
        QASE_PROJECT_ID: ${{ inputs.hb-qase-project-id }}
      run: |
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/upgrade/rke2k3s \
        --junitfile results.xml -- -timeout=60m -tags=recurring -v -run "TestWindowsKubernetesUpgradeTestSuite/TestUpgradeWindowsKubernetes";
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true