rancher:
  host: "<required>.<HB_AWS_ROUTE_53_ZONE>"
  adminPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
  insecure: true
  cleanup: true

awsCredentials:
  accessKey: "<required>"
  secretKey: "<required>"
  defaultRegion: "<required>"

terraform:
  provider: "<HB_PROVIDER>"
  downstreamClusterProvider: "<HB_PROVIDER>"
  resourcePrefix: "<HB_HOSTNAME_PREFIX>"
  localCluster: "rke2"
  cni: "<HB_CNI>"
  defaultClusterRoleForProjectMembers: "<HB_CLUSTER_ROLE_FOR_PROJECT_MEMBERS>"
  privateKeyPath: "<HB_TFP_SSH_PRIVATE_KEY_PATH>"
  awsCredentials:
    awsAccessKey: "<AWS_ACCESS_KEY_ID>"
    awsSecretKey: "<AWS_SECRET_ACCESS_KEY>"
  awsConfig:
    ami: "<HB_AWS_DUALSTACK_AMI>"
    awsKeyName: "<HB_SSH_PRIVATE_KEY_NAME>"
    awsInstanceType: "t3.xlarge"
    awsVolumeType: "<HB_AWS_VOLUME_TYPE>"
    region: "<HB_AWS_REGION>"
    awsSecurityGroups: ["<HB_AWS_SECURITY_GROUPS>"]
    awsSecurityGroupNames: <HB_AWS_SECURITY_GROUP_NAMES_COMMUNITY>
    awsSubnetID: "<HB_AWS_SUBNET_ID>"
    awsVpcID: "<HB_AWS_VPC_ID>"
    awsZoneLetter: "<HB_AWS_ZONE_LETTER>"
    awsRootSize: "<HB_AWS_ROOT_SIZE>"
    awsRoute53Zone: "<HB_AWS_ROUTE_53_ZONE>"
    clusterCIDR: "<HB_DUALSTACK_CLUSTER_CIDR>"
    serviceCIDR: "<HB_DUALSTACK_SERVICE_CIDR>"
    ipAddressType: "<HB_IP_ADDRESS_TYPE>"
    loadBalancerType: "<HB_LOAD_BALANCER_DUALSTACK_TYPE>"
    targetType: "<HB_TARGET_TYPE>"
    awsUser: "<HB_DUAL_STACK_AWS_USER>"
    sshConnectionType: "<HB_SSH_CONNECTION_TYPE>"
    timeout: "<HB_SSH_TIMEOUT>"
  standalone:
    chartVersion: "<required>"
    rancherTagVersion: "<required>"
    rancherChartRepository: "<required>"
    repo: "<required>"
    rancherImage: "<HB_RANCHER_IMAGE>"
    rancherHostname: "<required>"
    bootstrapPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
    certManagerVersion: "<HB_CERT_MANAGER_VERSION>"
    certType: "<HB_CERT_TYPE>"
    osUser: "<HB_DUAL_STACK_OS_USER>"
    osGroup: "<HB_DUAL_STACK_OS_GROUP>"
    registryPassword: "<HB_DOCKERHUB_PASSWORD>"
    registryUsername: "<HB_DOCKERHUB_USERNAME>"
    rke2Version: "<HB_RKE2_VERSION>"
terratest:
  pathToRepo: "<HB_PATH_TO_TFP_REPO>"
  standaloneLogging: false
  tfLogging: false
logging:
  level: "<HB_LOGGING_LEVEL>"
