FROM registry.suse.com/bci/golang:1.25

# Configure Go
ENV GOPATH=/root/go
ENV PATH=${PATH}:/root/go/bin

ENV WORKSPACE=${GOPATH}/src/github.com/rancher/tests

WORKDIR $WORKSPACE/validation

COPY [".", "$WORKSPACE"]

ARG GOTESTSUM_VERSION=v1.13.0
RUN go mod download && \
    go install gotest.tools/gotestsum@${GOTESTSUM_VERSION}

RUN mkdir /root/.ssh && chmod 600 .ssh/jenkins-*
RUN zypper install -y openssh
RUN for pem_file in .ssh/jenkins-*; do \
      ssh-keygen -f "$pem_file" -y > "/root/.ssh/$(basename "$pem_file").pub"; \
    done

RUN CGO_ENABLED=0

# necessary to run if statements using [[ ]]
SHELL ["/bin/bash", "-c"] 


ARG RKE_VERSION=v1.7.3
RUN echo "installing ${RKE_VERSION} version RKE" && \
    curl -fSL "https://github.com/rancher/rke/releases/download/${RKE_VERSION}/rke_linux-amd64" -o rke_linux-amd64 && \
    curl -fSL "https://github.com/rancher/rke/releases/download/${RKE_VERSION}/rke_linux-amd64.sha256" -o rke_linux-amd64.sha256 && \
    sha256sum -c rke_linux-amd64.sha256 && \
    mv rke_linux-amd64 /bin/rke && \
    chmod +x /bin/rke && \
    rm -f rke_linux-amd64.sha256


ARG CLI_VERSION
RUN if [[ -n "$CLI_VERSION" ]] ; then  \
        echo installing CLI version $CLI_VERSION ; \
    CLI_TAR="rancher-linux-amd64-$CLI_VERSION.tar.gz" ; \
    curl -fLO https://github.com/rancher/cli/releases/download/$CLI_VERSION/$CLI_TAR ; \
    curl -fLO https://github.com/rancher/cli/releases/download/$CLI_VERSION/sha256sum.txt ; \
    grep " $CLI_TAR$" sha256sum.txt | sha256sum -c - ; \
    tar -xf $CLI_TAR && \
        mv rancher-$CLI_VERSION/rancher /bin/rancher && \
    chmod +x /bin/rancher && \
    rm -f $CLI_TAR sha256sum.txt ; fi;