---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: VSphereMachineTemplate
metadata:
  name: <required>-control-plane
  namespace: fleet-default
spec:
  template:
    spec:
      datacenter: <required>
      datastore: <required>
      diskGiB: <required>
      folder: <required>
      memoryMiB: <required>
      network:
        devices:
        - dhcp4: true
          networkName: <required>
      numCPUs: <required>
      os: Linux
      resourcePool: <required>
      template: <required>
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: VSphereMachineTemplate
metadata:
  name: <required>-etcd
  namespace: fleet-default
spec:
  template:
    spec:
      datacenter: <required>
      datastore: <required>
      diskGiB: <required>
      folder: <required>
      memoryMiB: <required>
      network:
        devices:
        - dhcp4: true
          networkName: <required>
      numCPUs: <required>
      os: Linux
      resourcePool: <required>
      template: <required>
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: VSphereMachineTemplate
metadata:
  name: <required>-worker
  namespace: fleet-default
spec:
  template:
    spec:
      datacenter: <required>
      datastore: <required>
      diskGiB: <required>
      folder: <required>
      memoryMiB: <required>
      network:
        devices:
        - dhcp4: true
          networkName: <required>
      numCPUs: <required>
      os: Linux
      resourcePool: <required>
      template: <required>
---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-cpi-creds
  namespace: fleet-default
  annotations:
    rke.cattle.io/object-authorized-for-clusters: <required>
    provisioning.cattle.io/sync-bootstrap: "true"
    provisioning.cattle.io/sync-target-namespace: kube-system
type: Opaque
stringData:
  <required>.username: <required>
  <required>.password: <required>
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: VSphereCluster
metadata:
  name: <required>
  namespace: fleet-default
spec:
  identityRef:
    kind: VSphereClusterIdentity
    name: vsphere-cluster-identity
  server: <required>
---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: <required>
  namespace: fleet-default
spec:
  kubernetesVersion: <required>
  rkeConfig:
    infrastructureRef:
      kind: VSphereCluster
      name: <required>
      namespace: fleet-default
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    machinePools:
      - name: etcd
        etcdRole: <required>
        controlPlaneRole: <required>
        workerRole: <required>
        quantity: <required>
        machineConfigRef:
          kind: VSphereMachineTemplate
          name: <required>-etcd
          namespace: fleet-default
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      - name: control-plane
        etcdRole: <required>
        controlPlaneRole: <required>
        workerRole: <required>
        quantity: <required>
        machineConfigRef:
          kind: VSphereMachineTemplate
          name: <required>-control-plane
          namespace: fleet-default
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      - name: worker
        etcdRole: <required>
        controlPlaneRole: <required>
        workerRole: <required>
        quantity: <required>
        machineConfigRef:
          kind: VSphereMachineTemplate
          name: <required>-worker
          namespace: fleet-default
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    machineGlobalConfig:
      disable-kube-proxy: false
      etcd-expose-metrics: false
      ingress-controller: traefik
      protect-kernel-defaults: false
      disable:
        - rancher-vsphere-csi
      cloud-provider-name: rancher-vsphere
    machineSelectorConfig:
      - config:
          disable-cloud-controller: true
          kube-controller-manager-arg:
            - cloud-provider=external
          kubelet-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchExpressions:
            - key: rke.cattle.io/control-plane-role
              operator: In
              values:
                - 'true'
      - config:
          disable-cloud-controller: true
          kubelet-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchExpressions:
            - key: rke.cattle.io/etcd-role
              operator: In
              values:
                - 'true'
      - config:
          kubelet-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchExpressions:
            - key: rke.cattle.io/worker-role
              operator: In
              values:
                - 'true'
    chartValues:
      rancher-vsphere-cpi:
        vCenter:
          datacenters: <required>
          host: <required>
          credentialsSecret:
            generate: false