---
name: Run Daily Provisioning Test Suites
description: "Runs daily provisioning test suites"
runs:
  using: composite
  steps:
    - name: Run K3S Provisioning Tests
      run: |
        set +e
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/k3s \
        --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v;
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true

    - name: Run RKE2 Provisioning Tests
      run: |
        set +e
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/rke2 \
        --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v;
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter
      shell: bash
      continue-on-error: true