---
name: Run Daily Provisioning Test Suites
description: "Runs daily provisioning test suites"
runs:
  using: composite
  steps:
    - name: Run K3S Provisioning Tests
      id: k3s
      run: |
        set +e
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/k3s \
        --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v;
        k3s_exit=$?;
        echo "k3s_exit=$k3s_exit" >> $GITHUB_ENV;
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter;
      shell: bash
      continue-on-error: true

    - name: Run RKE2 Provisioning Tests
      id: rke2
      run: |
        set +e
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/provisioning/rke2 \
        --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=recurring -v;
        rke2_exit=$?;
        echo "rke2_exit=$rke2_exit" >> $GITHUB_ENV;
        ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
        ./validation/reporter;
      shell: bash
      continue-on-error: true

    - name: Show failed tests
      run: |
        failed=0
        if [ "$k3s_exit" -ne 0 ]; then
          echo "Failed K3S tests:"
          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results.json
          failed=1
        fi

        if [ "$rke2_exit" -ne 0 ]; then
          echo "Failed RKE2 tests:"
          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results.json
          failed=1
        fi

        if [ "$failed" -eq 1 ]; then
          exit 1
        fi
      shell: bash