name: Verify Changes

on:
  push:
    branches:
      - 'stable'
      - 'main'
  pull_request:
    branches:
      - 'stable'
      - 'main'

jobs:
  verify-changes:
    name: verify-changes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          ref: ${{ github.head_ref }}

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: './go.mod'

      - name: Go Version
        run: go version

      - name: Generate Golang
        run: |
          export PATH=$PATH:/home/runner/go/bin/
      
      - name: Verify Go Mod
        run: ./.github/scripts/check-gomod.sh

      - name: Build Packages
        run: ./.github/scripts/go-build.sh

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837 # v6.5.0
        with:
          # Patch version isn't needed; https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#internals
          version: v1.64.5
          # only run on changed files in this PR / push
          only-new-issues: true