---
name: Registries Cluster Provisioning

on:
  schedule:
    - cron: "0 6 * * 4"
  workflow_dispatch:
    inputs:
      rancher_version:
        description: "Rancher tag version"
        required: false
      rancher_chart_version:
        description: "Rancher chart version"
        required: false
      reporting:
        description: "Enable reporting to Qase and Slack"
        required: false
        default: false
        type: boolean
      local_cluster_type:
        description: "Local cluster type to setup Rancher"
        required: true
        default: "rke2"
        type: choice
        options:
          - rke2
  workflow_call:
    inputs:
      rancher_version:
        description: "Rancher tag version provided from check-rancher-tag workflow"
        required: false
        type: string
      rancher_chart_version:
        description: "Rancher chart version provided from check-rancher-tag workflow"
        required: false
        type: string

permissions:
  id-token: write
  contents: read

env:
  CLOUD_PROVIDER_VERSION: "6.50.0"
  LOCAL_CLUSTER_TYPE: >-
    ${{ 
      (github.event_name == 'workflow_dispatch' && github.event.inputs.local_cluster_type) || 
      (github.event_name == 'schedule' && 'rke2') || 'rke2' 
    }}
  REPORTING_ENABLED: >-
    ${{
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_call' ||
      github.actor == 'github-actions[bot]' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.reporting == 'true' )
    }}

jobs:
  v2-16:
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.rancher_version, 'head'))
    name: ${{ github.event.inputs.rancher_version }}
    runs-on: ubuntu-latest
    environment: prime-head
    env:
      HOSTNAME_PREFIX: "r216"
      RANCHER2_PROVIDER_VERSION: "${{ vars.RANCHER2_PROVIDER_VERSION_2_15 }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          submodules: recursive

      - name: Checkout tfp-automation repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          repository: rancher/tfp-automation
          path: tfp-automation

      - name: Set up local rancher2 Terraform provider
        if: contains(env.RANCHER2_PROVIDER_VERSION, '-rc')
        run: chmod +x ./tfp-automation/scripts/setup-provider.sh && ./tfp-automation/scripts/setup-provider.sh rancher2 v${{ env.RANCHER2_PROVIDER_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ fromJSON(env.HB_AWS_REGION).value }}

      - name: Get AWS credentials from Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@3a411b6ec5cace3d626412dd917e7bfeac242cfa #v3
        with:
          secret-ids: |
            AWS_ACCESS_KEY, ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_KEY, ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            HB_SSH_PRIVATE_KEY, HB_SSH_PRIVATE_KEY
            HB_SSH_PRIVATE_KEY_NAME, HB_SSH_PRIVATE_KEY_NAME
            HB_WINDOWS_SSH_PRIVATE_KEY, HB_WINDOWS_SSH_PRIVATE_KEY
            HB_WINDOWS_SSH_PRIVATE_KEY_NAME, HB_WINDOWS_SSH_PRIVATE_KEY_NAME
            HB_PRIVATE_FULL_CHAIN, HB_PRIVATE_FULL_CHAIN
            HB_PRIVATE_FULL_CHAIN_NAME, HB_PRIVATE_FULL_CHAIN_NAME
            HB_PRIVATE_CERT_KEY, HB_PRIVATE_CERT_KEY
            HB_PRIVATE_CERT_KEY_NAME, HB_PRIVATE_CERT_KEY_NAME
            HB_AWS_REGION, HB_AWS_REGION
            HB_TERRAFORM_VERSION, HB_TERRAFORM_VERSION
            HB_RANCHER_ADMIN_PASSWORD, HB_RANCHER_ADMIN_PASSWORD
            HB_RANCHER_VERSION_HEAD, HB_RANCHER_VERSION_HEAD
            HB_RELEASED_RANCHER_CHART_VERSION_2_15, HB_RELEASED_RANCHER_CHART_VERSION_2_15
            HB_RKE2_VERSION_2_16, HB_RKE2_VERSION_2_16
            HB_K3S_VERSION_2_16, HB_K3S_VERSION_2_16
            HB_K3S_VERSION_SUFFIX, HB_K3S_VERSION_SUFFIX
            HB_QASE_RECURRING_TEST_RUN_ID_2_16, HB_QASE_RECURRING_TEST_RUN_ID_2_16
            HB_QA_PRIVATE_REGISTRY_NAME, HB_QA_PRIVATE_REGISTRY_NAME
            HB_QASE_AUTOMATION_TOKEN, HB_QASE_AUTOMATION_TOKEN
            HB_QASE_PROJECT_ID, HB_QASE_PROJECT_ID
            HB_RANCHER_HELM_CHART_URL, HB_RANCHER_HELM_CHART_URL
            HB_SLACK_WEBHOOK_URL, HB_SLACK_WEBHOOK_URL

      - name: "Fetch and Set DockerHub Credentials"
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 #v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials username | DOCKERHUB_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials password | DOCKERHUB_PASSWORD

      - name: Mask Dockerhub Credentials
        run: |
          echo "::add-mask::${{ env.DOCKERHUB_USERNAME }}"
          echo "::add-mask::${{ env.DOCKERHUB_PASSWORD }}"

      - name: Whitelist Runner IP
        uses: ./.github/actions/whitelist-runner-ip
        with:
          prefix-list-id: ${{ fromJSON(env.HB_AWS_MANAGED_PREFIX_LIST_ID).value }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Set up SSH Keys
        uses: ./.github/actions/setup-ssh-keys
        with:
          ssh-private-key: ${{ fromJSON(env.HB_SSH_PRIVATE_KEY).value }}
          ssh-private-key-name: ${{ fromJSON(env.HB_SSH_PRIVATE_KEY_NAME).value }}
          windows-ssh-private-key: ${{ fromJSON(env.HB_WINDOWS_SSH_PRIVATE_KEY).value }}
          windows-ssh-private-key-name: ${{ fromJSON(env.HB_WINDOWS_SSH_PRIVATE_KEY_NAME).value }}

      - name: Set up certificates
        id: setup-certs
        uses: ./.github/actions/setup-certs
        with:
          private-full-chain: ${{ fromJSON(env.HB_PRIVATE_FULL_CHAIN).value }}
          private-full-chain-name: ${{ fromJSON(env.HB_PRIVATE_FULL_CHAIN_NAME).value }}
          private-cert-key: ${{ fromJSON(env.HB_PRIVATE_CERT_KEY).value }}
          private-cert-key-name: ${{ fromJSON(env.HB_PRIVATE_CERT_KEY_NAME).value }}

      - name: Uniquify hostname prefix
        uses: ./.github/actions/uniquify-hostname

      - name: Set Rancher version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_VERSION
          value: |
            ${{
              github.event.inputs.rancher_version ||
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_version) ||
              (github.event_name == 'schedule' && fromJSON(env.HB_RANCHER_VERSION_HEAD).value)
            }}

      - name: Set Rancher chart version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_CHART_VERSION
          value: |
            ${{ 
              github.event.inputs.rancher_chart_version || 
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_chart_version) ||
              (github.event_name == 'schedule' && fromJSON(env.HB_RANCHER_VERSION_2_15_HEAD).value)
            }}

      - name: Get Qase ID
        id: get-qase-id
        uses: ./.github/actions/get-qase-id
        with:
          qase_recurring_id: ${{ fromJSON(env.HB_QASE_RECURRING_TEST_RUN_ID_2_16).value }}

      - name: Retrieve and set ECR password
        id: get-ecr-password
        uses: ./.github/actions/get-ecr-password

      - name: Create config.yaml
        run: |
          cat > config.yaml <<EOF
          rancher:
            host: "${{ env.HOSTNAME_PREFIX }}.<HB_AWS_ROUTE_53_ZONE>"
            adminPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
            insecure: true
            cleanup: true
          terraform:
            cni: "<HB_CNI>"
            defaultClusterRoleForProjectMembers: "true"
            enableNetworkPolicy: false
            localCluster: "${{ env.LOCAL_CLUSTER_TYPE }}"
            provider: "<HB_PROVIDER_AMAZON>"
            privateKeyPath: "<HB_TFP_SSH_PRIVATE_KEY_PATH>"
            privateFullChainPath: "${{ steps.setup-certs.outputs.private-full-chain-tfp-path }}"
            privateCertKeyPath: "${{ steps.setup-certs.outputs.private-cert-key-tfp-path }}"
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            awsCredentials:
              awsAccessKey: "$AWS_ACCESS_KEY"
              awsSecretKey: "$AWS_SECRET_KEY"
            awsConfig:
              ami: "<HB_DEFAULT_AMI>"
              awsKeyName: "<HB_SSH_PRIVATE_KEY_NAME>"
              awsInstanceType: "<HB_AWS_INSTANCE_TYPE>"
              awsVolumeType: "<HB_AWS_VOLUME_TYPE>"
              region: "<HB_AWS_REGION>"
              awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS>]
              awsSecurityGroupNames: [<HB_AWS_SECURITY_GROUP_NAMES>]
              awsSubnetID: "<HB_AWS_SUBNET_ID>"
              awsVpcID: "<HB_AWS_VPC_ID>"
              awsZoneLetter: "<HB_AWS_ZONE_LETTER>"
              awsRootSize: <HB_AWS_ROOT_SIZE>
              registryRootSize: <HB_AWS_ROOT_SIZE_REGISTRY>
              awsRoute53Zone: "<HB_AWS_ROUTE_53_ZONE>"
              awsUser: "<HB_AWS_OS_USER>"
              sshConnectionType: "<HB_SSH_CONNECTION_TYPE>" 
              timeout: "<HB_TIMEOUT>"
              ipAddressType: "<HB_IP_ADDRESS_TYPE>"
              loadBalancerType: "<HB_LOAD_BALANCER_TYPE>"
              targetType: "<HB_TARGET_TYPE>"
            standalone:
              bootstrapPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
              certManagerVersion: "<HB_CERT_MANAGER_VERSION>"
              chartVersion: "${{ env.RANCHER_CHART_VERSION }}"
              k3sVersion: "<HB_K3S_VERSION_2_16><HB_K3S_VERSION_SUFFIX>"
              osUser: "<HB_AWS_OS_USER>"
              osGroup: "<HB_OS_GROUP>"
              rancherAgentImage: "<HB_RANCHER_AGENT_IMAGE>"
              rancherChartRepository: "<HB_RANCHER_HELM_CHART_URL>"
              rancherHostname: "${{ env.HOSTNAME_PREFIX }}.<HB_AWS_ROUTE_53_ZONE>"
              rancherImage: "<HB_RANCHER_IMAGE>"
              rancherTagVersion: "${{ env.RANCHER_VERSION }}"
              registryPassword: "${{ env.DOCKERHUB_PASSWORD }}"
              registryUsername: "${{ env.DOCKERHUB_USERNAME }}"
              repo: "<HB_RANCHER_REPO>"
              rke2Version: "<HB_RKE2_VERSION_2_16>"
            standaloneRegistry:
              assetsPath: "<HB_ASSETS_PATH>"
              createAuthGlobalRegistry: true
              registryName: "${{ env.HOSTNAME_PREFIX }}"
              registryPassword: "${{ env.HOSTNAME_PREFIX }}-pass"
              registryUsername: "${{ env.HOSTNAME_PREFIX }}-user"
              ecrUsername: "<HB_ECR_USERNAME>"
              ecrPassword: "${{ steps.get-ecr-password.outputs.password }}"
              ecrURI: "<HB_ECR_URI>"
              useAuthGlobalRegistry: true
          terratest:
            pathToRepo: "<HB_PATH_TO_REPO>"
            standaloneLogging: <HB_TERRAFORM_LOGGING>

          clusterConfig:
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            cni: "<HB_CNI>"
            provider: "<HB_PROVIDER_AMAZON>"
            nodeProvider: "ec2"
            pathToRepo: "<HB_PATH_TO_TESTS_REPO>"

          logging:
            level: "<HB_LOGGING_LEVEL>"

          awsCredentials:
            secretKey: "$AWS_SECRET_KEY"
            accessKey: "$AWS_ACCESS_KEY"
            defaultRegion: "<HB_AWS_REGION>"

          awsMachineConfigs:
            region: "<HB_AWS_REGION>"
            awsMachineConfig:
            - roles: ["etcd", "controlplane", "worker"]
              ami: "<HB_DEFAULT_AMI>"
              instanceType: "<HB_AWS_INSTANCE_TYPE>"
              sshUser: "<HB_AWS_OS_USER>"
              vpcId: "<HB_AWS_VPC_ID>"
              subnetId: "<HB_AWS_SUBNET_ID>"
              volumeType: "<HB_AWS_VOLUME_TYPE>"
              zone: "<HB_AWS_ZONE_LETTER>"
              retries: "5"
              rootSize: "<HB_AWS_ROOT_SIZE>"
              iamInstanceProfile: "<HB_AWS_IAM_PROFILE>"

          awsEC2Configs:
            region: "<HB_AWS_REGION>"
            awsSecretAccessKey: "$AWS_SECRET_KEY"
            awsAccessKeyID: "$AWS_ACCESS_KEY"
            awsEC2Config:
              - awsRegionAZ: "<HB_AWS_REGION><HB_AWS_ZONE_LETTER>"
                awsAMI: "<HB_AWS_AMI>"
                instanceType: "<HB_AWS_INSTANCE_TYPE>"
                awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS>]
                awsSubnetID: "<HB_AWS_SUBNET_ID>"
                awsSSHKeyName: "<HB_SSH_PRIVATE_KEY_NAME>.pem"
                awsCICDInstanceTag: "rancher-validation"
                awsIAMProfile: "<HB_AWS_IAM_PROFILE>"
                awsUser: "<HB_AWS_USER>"
                volumeSize: <HB_AWS_ROOT_SIZE>
                roles: ["etcd", "controlplane", "worker"]
              - instanceType: "<HB_AWS_WINDOWS_INSTANCE_TYPE>"
                awsRegionAZ: "<HB_AWS_REGION><HB_AWS_ZONE_LETTER>"
                awsAMI: "<HB_WINDOWS_2022_AMI>"
                awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS>]
                awsSubnetID: "<HB_AWS_SUBNET_ID>"
                awsSSHKeyName: "<HB_WINDOWS_SSH_PRIVATE_KEY_NAME>.pem"
                awsCICDInstanceTag: "rancher-validation"
                awsUser: "<HB_AWS_WINDOWS_USER>"
                volumeSize: <HB_AWS_ROOT_SIZE>
                roles: ["windows"]
          sshPath: 
            sshPath: "<HB_SSH_PRIVATE_KEY_PATH>"
          EOF

      - name: Export CATTLE_TEST_CONFIG
        run: echo "CATTLE_TEST_CONFIG=${{ github.workspace }}/config.yaml" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go environment
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 #v6
        with:
          go-version-file: "./go.mod"

      - name: Build Packages
        run: ./.github/scripts/go-build.sh

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@c4a0df2e75a225d979a444342dd3db752b53619f

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4
        with:
          terraform_version: "${{ fromJSON(env.HB_TERRAFORM_VERSION).value }}"
          terraform_wrapper: false

      - name: Creating Rancher server
        run: go run /home/runner/work/tests/tests/validation/recurring/infrastructure/setuprancher/registry/main.go

      - name: Run Provisioning tests
        env:
          QASE_TEST_RUN_ID: ${{ steps.get-qase-id.outputs.id }}
          QASE_AUTOMATION_TOKEN: ${{ fromJSON(env.HB_QASE_AUTOMATION_TOKEN).value }}
          QASE_CUSTOM_FIELD_FILTER: Hostbusters
          QASE_SCHEMA_PREFIX: hostbusters
          QASE_PROJECT_ID: ${{ fromJSON(env.HB_QASE_PROJECT_ID).value }}
        uses: ./.github/actions/run-hostbusters-provisioning
        with:
          reporting: ${{ env.REPORTING_ENABLED }}
          tags: registries

      - name: Cleanup Infrastructure
        if: always()
        working-directory: tfp-automation/modules/registries/authGlobal
        run: terraform destroy -auto-approve > /dev/null 2>&1

      - name: Refresh AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ fromJSON(env.HB_AWS_REGION).value }}

      - name: AWS Custodian Infrastructure Cleanup
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Downstream Cleanup - Node driver
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "auto-${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Downstream Cleanup - Custom
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "rancher-validation${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Revoke Runner IP
        if: always()
        uses: ./.github/actions/revoke-runner-ip
        with:
          prefix-list-id: ${{ secrets.AWS_MANAGED_PREFIX_LIST_ID }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Set job status output
        if: always()
        run: echo "job_status=${{ job.status }}" >> $GITHUB_OUTPUT
        id: set-job-status

      - name: Reporting Results to Slack
        if: always() && env.REPORTING_ENABLED == 'true'
        uses: ./.github/actions/report-to-slack
        with:
          rancher-version: ${{ env.RANCHER_VERSION }}
          job-status: ${{ steps.set-job-status.outputs.job_status }}
          slack-webhook-url: ${{ fromJSON(env.HB_SLACK_WEBHOOK_URL).value }}
  
  v2-15:
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.rancher_version, 'v2.15-head'))
    name: ${{ github.event.inputs.rancher_version }}
    runs-on: ubuntu-latest
    environment: prime-head
    env:
      HOSTNAME_PREFIX: "r215"
      RANCHER2_PROVIDER_VERSION: "${{ vars.RANCHER2_PROVIDER_VERSION_2_15 }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          submodules: recursive

      - name: Checkout tfp-automation repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          repository: rancher/tfp-automation
          path: tfp-automation

      - name: Set up local rancher2 Terraform provider
        if: contains(env.RANCHER2_PROVIDER_VERSION, '-rc')
        run: chmod +x ./tfp-automation/scripts/setup-provider.sh && ./tfp-automation/scripts/setup-provider.sh rancher2 v${{ env.RANCHER2_PROVIDER_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Get AWS credentials from Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@3a411b6ec5cace3d626412dd917e7bfeac242cfa #v3
        with:
          secret-ids: |
            AWS_ACCESS_KEY, ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_KEY, ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            HB_SSH_PRIVATE_KEY, HB_SSH_PRIVATE_KEY
            HB_SSH_PRIVATE_KEY_NAME, HB_SSH_PRIVATE_KEY_NAME
            HB_WINDOWS_SSH_PRIVATE_KEY, HB_WINDOWS_SSH_PRIVATE_KEY
            HB_WINDOWS_SSH_PRIVATE_KEY_NAME, HB_WINDOWS_SSH_PRIVATE_KEY_NAME
            HB_PRIVATE_FULL_CHAIN, HB_PRIVATE_FULL_CHAIN
            HB_PRIVATE_FULL_CHAIN_NAME, HB_PRIVATE_FULL_CHAIN_NAME
            HB_PRIVATE_CERT_KEY, HB_PRIVATE_CERT_KEY
            HB_PRIVATE_CERT_KEY_NAME, HB_PRIVATE_CERT_KEY_NAME
            HB_AWS_REGION, HB_AWS_REGION
            HB_TERRAFORM_VERSION, HB_TERRAFORM_VERSION
            HB_RANCHER_ADMIN_PASSWORD, HB_RANCHER_ADMIN_PASSWORD
            HB_RANCHER_VERSION_2_15_HEAD, HB_RANCHER_VERSION_2_15_HEAD
            HB_RELEASED_RANCHER_CHART_VERSION_2_15, HB_RELEASED_RANCHER_CHART_VERSION_2_15
            HB_RKE2_VERSION_2_15, HB_RKE2_VERSION_2_15
            HB_K3S_VERSION_2_15, HB_K3S_VERSION_2_15
            HB_K3S_VERSION_SUFFIX, HB_K3S_VERSION_SUFFIX
            HB_QASE_RECURRING_TEST_RUN_ID_2_15, HB_QASE_RECURRING_TEST_RUN_ID_2_15
            HB_QA_PRIVATE_REGISTRY_NAME, HB_QA_PRIVATE_REGISTRY_NAME
            HB_QASE_AUTOMATION_TOKEN, HB_QASE_AUTOMATION_TOKEN
            HB_QASE_PROJECT_ID, HB_QASE_PROJECT_ID
            HB_RANCHER_HELM_CHART_URL, HB_RANCHER_HELM_CHART_URL
            HB_SLACK_WEBHOOK_URL, HB_SLACK_WEBHOOK_URL

      - name: "Fetch and Set DockerHub Credentials"
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 #v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials username | DOCKERHUB_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials password | DOCKERHUB_PASSWORD

      - name: Mask Dockerhub Credentials
        run: |
          echo "::add-mask::${{ env.DOCKERHUB_USERNAME }}"
          echo "::add-mask::${{ env.DOCKERHUB_PASSWORD }}"

      - name: Whitelist Runner IP
        uses: ./.github/actions/whitelist-runner-ip
        with:
          prefix-list-id: ${{ fromJSON(env.HB_AWS_MANAGED_PREFIX_LIST_ID).value }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Set up SSH Keys
        uses: ./.github/actions/setup-ssh-keys
        with:
          ssh-private-key: ${{ fromJSON(env.HB_SSH_PRIVATE_KEY).value }}
          ssh-private-key-name: ${{ fromJSON(env.HB_SSH_PRIVATE_KEY_NAME).value }}
          windows-ssh-private-key: ${{ fromJSON(env.HB_WINDOWS_SSH_PRIVATE_KEY).value }}
          windows-ssh-private-key-name: ${{ fromJSON(env.HB_WINDOWS_SSH_PRIVATE_KEY_NAME).value }}

      - name: Set up certificates
        id: setup-certs
        uses: ./.github/actions/setup-certs
        with:
          private-full-chain: ${{ fromJSON(env.HB_PRIVATE_FULL_CHAIN).value }}
          private-full-chain-name: ${{ fromJSON(env.HB_PRIVATE_FULL_CHAIN_NAME).value }}
          private-cert-key: ${{ fromJSON(env.HB_PRIVATE_CERT_KEY).value }}
          private-cert-key-name: ${{ fromJSON(env.HB_PRIVATE_CERT_KEY_NAME).value }}

      - name: Uniquify hostname prefix
        uses: ./.github/actions/uniquify-hostname

      - name: Set Rancher version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_VERSION
          value: |
            ${{
              github.event.inputs.rancher_version ||
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_version) ||
              (github.event_name == 'schedule' && fromJSON(env.HB_RANCHER_VERSION_2_15_HEAD).value)
            }}

      - name: Set Rancher chart version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_CHART_VERSION
          value: |
            ${{ 
              github.event.inputs.rancher_chart_version || 
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_chart_version) ||
              (github.event_name == 'schedule' && fromJSON(env.HB_RELEASED_RANCHER_CHART_VERSION_2_15).value)
            }}

      - name: Get Qase ID
        id: get-qase-id
        uses: ./.github/actions/get-qase-id
        with:
          qase_recurring_id: ${{ fromJSON(env.HB_QASE_RECURRING_TEST_RUN_ID_2_15).value }}

      - name: Retrieve and set ECR password
        id: get-ecr-password
        uses: ./.github/actions/get-ecr-password

      - name: Create config.yaml
        run: |
          cat > config.yaml <<EOF
          rancher:
            host: "${{ env.HOSTNAME_PREFIX }}.<HB_AWS_ROUTE_53_ZONE>"
            adminPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
            insecure: true
            cleanup: true
          terraform:
            cni: "<HB_CNI>"
            defaultClusterRoleForProjectMembers: "true"
            enableNetworkPolicy: false
            localCluster: "${{ env.LOCAL_CLUSTER_TYPE }}"
            provider: "<HB_PROVIDER_AMAZON>"
            privateKeyPath: "<HB_TFP_SSH_PRIVATE_KEY_PATH>"
            privateFullChainPath: "${{ steps.setup-certs.outputs.private-full-chain-tfp-path }}"
            privateCertKeyPath: "${{ steps.setup-certs.outputs.private-cert-key-tfp-path }}"
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            awsCredentials:
              awsAccessKey: "$AWS_ACCESS_KEY"
              awsSecretKey: "$AWS_SECRET_KEY"
            awsConfig:
              ami: "<HB_AWS_AMI>"
              awsKeyName: "<HB_SSH_PRIVATE_KEY_NAME>"
              awsInstanceType: "<HB_AWS_INSTANCE_TYPE>"
              awsVolumeType: "<HB_AWS_VOLUME_TYPE>"
              region: "<HB_AWS_REGION>"
              awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS>]
              awsSecurityGroupNames: [<HB_AWS_SECURITY_GROUP_NAMES>]
              awsSubnetID: "<HB_AWS_SUBNET_ID>"
              awsVpcID: "<HB_AWS_VPC_ID>"
              awsZoneLetter: "<HB_AWS_ZONE_LETTER>"
              awsRootSize: <HB_AWS_ROOT_SIZE>
              registryRootSize: <HB_AWS_ROOT_SIZE_REGISTRY>
              awsRoute53Zone: "<HB_AWS_ROUTE_53_ZONE>"
              awsUser: "<HB_AWS_USER>"
              sshConnectionType: "<HB_SSH_CONNECTION_TYPE>" 
              timeout: "<HB_TIMEOUT>"
              ipAddressType: "<HB_IP_ADDRESS_TYPE>"
              loadBalancerType: "<HB_LOAD_BALANCER_TYPE>"
              targetType: "<HB_TARGET_TYPE>"
            standalone:
              bootstrapPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
              certManagerVersion: "<HB_CERT_MANAGER_VERSION>"
              chartVersion: "${{ env.RANCHER_CHART_VERSION }}"
              k3sVersion: "<HB_K3S_VERSION_2_15><HB_K3S_VERSION_SUFFIX>"
              osUser: "<HB_OS_USER>"
              osGroup: "<HB_OS_GROUP>"
              rancherAgentImage: "<HB_RANCHER_AGENT_IMAGE>"
              rancherChartRepository: "<HB_RANCHER_HELM_CHART_URL>"
              rancherHostname: "${{ env.HOSTNAME_PREFIX }}.<HB_AWS_ROUTE_53_ZONE>"
              rancherImage: "<HB_RANCHER_IMAGE>"
              rancherTagVersion: "${{ env.RANCHER_VERSION }}"
              registryPassword: "${{ env.DOCKERHUB_PASSWORD }}"
              registryUsername: "${{ env.DOCKERHUB_USERNAME }}"
              repo: "<HB_RANCHER_REPO>"
              rke2Version: "<HB_RKE2_VERSION_2_15>"
            standaloneRegistry:
              assetsPath: "<HB_ASSETS_PATH>"
              createAuthGlobalRegistry: true
              registryName: "${{ env.HOSTNAME_PREFIX }}"
              registryPassword: "${{ env.HOSTNAME_PREFIX }}-pass"
              registryUsername: "${{ env.HOSTNAME_PREFIX }}-user"
              ecrUsername: "<HB_ECR_USERNAME>"
              ecrPassword: "${{ steps.get-ecr-password.outputs.password }}"
              ecrURI: "<HB_ECR_URI>"
              useAuthGlobalRegistry: true
          terratest:
            pathToRepo: "<HB_PATH_TO_REPO>"
            standaloneLogging: <HB_TERRAFORM_LOGGING>

          clusterConfig:
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            cni: "<HB_CNI>"
            provider: "<HB_PROVIDER_AMAZON>"
            nodeProvider: "ec2"
            pathToRepo: "<HB_PATH_TO_TESTS_REPO>"

          logging:
            level: "<HB_LOGGING_LEVEL>"

          awsCredentials:
            secretKey: "$AWS_SECRET_KEY"
            accessKey: "$AWS_ACCESS_KEY"
            defaultRegion: "<HB_AWS_REGION>"

          awsMachineConfigs:
            region: "<HB_AWS_REGION>"
            awsMachineConfig:
            - roles: ["etcd", "controlplane", "worker"]
              ami: "<HB_AWS_AMI>"
              instanceType: "<HB_AWS_INSTANCE_TYPE>"
              sshUser: "<HB_AWS_USER>"
              vpcId: "<HB_AWS_VPC_ID>"
              subnetId: "<HB_AWS_SUBNET_ID>"
              volumeType: "<HB_AWS_VOLUME_TYPE>"
              zone: "<HB_AWS_ZONE_LETTER>"
              retries: "5"
              rootSize: "<HB_AWS_ROOT_SIZE>"
              iamInstanceProfile: "<HB_AWS_IAM_PROFILE>"

          awsEC2Configs:
            region: "<HB_AWS_REGION>"
            awsSecretAccessKey: "$AWS_SECRET_KEY"
            awsAccessKeyID: "$AWS_ACCESS_KEY"
            awsEC2Config:
              - awsRegionAZ: "<HB_AWS_REGION><HB_AWS_ZONE_LETTER>"
                awsAMI: "<HB_AWS_AMI>"
                instanceType: "<HB_AWS_INSTANCE_TYPE>"
                awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS>]
                awsSubnetID: "<HB_AWS_SUBNET_ID>"
                awsSSHKeyName: "<HB_SSH_PRIVATE_KEY_NAME>.pem"
                awsCICDInstanceTag: "rancher-validation"
                awsIAMProfile: "<HB_AWS_IAM_PROFILE>"
                awsUser: "<HB_AWS_USER>"
                volumeSize: <HB_AWS_ROOT_SIZE>
                roles: ["etcd", "controlplane", "worker"]
              - instanceType: "<HB_AWS_WINDOWS_INSTANCE_TYPE>"
                awsRegionAZ: "<HB_AWS_REGION><HB_AWS_ZONE_LETTER>"
                awsAMI: "<HB_WINDOWS_2022_AMI>"
                awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS>]
                awsSubnetID: "<HB_AWS_SUBNET_ID>"
                awsSSHKeyName: "<HB_WINDOWS_SSH_PRIVATE_KEY_NAME>.pem"
                awsCICDInstanceTag: "rancher-validation"
                awsUser: "<HB_AWS_WINDOWS_USER>"
                volumeSize: <HB_AWS_ROOT_SIZE>
                roles: ["windows"]
          sshPath: 
            sshPath: "<HB_SSH_PRIVATE_KEY_PATH>"
          EOF

      - name: Export CATTLE_TEST_CONFIG
        run: echo "CATTLE_TEST_CONFIG=${{ github.workspace }}/config.yaml" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go environment
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 #v6
        with:
          go-version-file: "./go.mod"

      - name: Build Packages
        run: ./.github/scripts/go-build.sh

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@c4a0df2e75a225d979a444342dd3db752b53619f

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4
        with:
          terraform_version: "${{ fromJSON(env.HB_TERRAFORM_VERSION).value }}"
          terraform_wrapper: false

      - name: Creating Rancher server
        run: go run /home/runner/work/tests/tests/validation/recurring/infrastructure/setuprancher/registry/main.go

      - name: Run Provisioning tests
        env:
          QASE_TEST_RUN_ID: ${{ steps.get-qase-id.outputs.id }}
          QASE_AUTOMATION_TOKEN: ${{ fromJSON(env.HB_QASE_AUTOMATION_TOKEN).value }}
          QASE_CUSTOM_FIELD_FILTER: Hostbusters
          QASE_SCHEMA_PREFIX: hostbusters
          QASE_PROJECT_ID: ${{ fromJSON(env.HB_QASE_PROJECT_ID).value }}
        uses: ./.github/actions/run-hostbusters-provisioning
        with:
          reporting: ${{ env.REPORTING_ENABLED }}
          tags: registries

      - name: Cleanup Infrastructure
        if: always()
        working-directory: tfp-automation/modules/registries/authGlobal
        run: terraform destroy -auto-approve > /dev/null 2>&1

      - name: Refresh AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ fromJSON(env.HB_AWS_REGION).value }}

      - name: AWS Custodian Infrastructure Cleanup
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Downstream Cleanup - Node driver
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "auto-${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Downstream Cleanup - Custom
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "rancher-validation${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Revoke Runner IP
        if: always()
        uses: ./.github/actions/revoke-runner-ip
        with:
          prefix-list-id: ${{ secrets.AWS_MANAGED_PREFIX_LIST_ID }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Set job status output
        if: always()
        run: echo "job_status=${{ job.status }}" >> $GITHUB_OUTPUT
        id: set-job-status

      - name: Reporting Results to Slack
        if: always() && env.REPORTING_ENABLED == 'true'
        uses: ./.github/actions/report-to-slack
        with:
          rancher-version: ${{ env.RANCHER_VERSION }}
          job-status: ${{ steps.set-job-status.outputs.job_status }}
          slack-webhook-url: ${{ fromJSON(env.HB_SLACK_WEBHOOK_URL).value }}

  v2-14:
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.rancher_version, 'v2.14-head'))
    name: ${{ github.event.inputs.rancher_version }}
    runs-on: ubuntu-latest
    environment: prime-head
    env:
      HOSTNAME_PREFIX: "r214"
      RANCHER2_PROVIDER_VERSION: "${{ vars.RANCHER2_PROVIDER_VERSION_2_14 }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          submodules: recursive

      - name: Checkout tfp-automation repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          repository: rancher/tfp-automation
          path: tfp-automation

      - name: Set up local rancher2 Terraform provider
        if: contains(env.RANCHER2_PROVIDER_VERSION, '-rc')
        run: chmod +x ./tfp-automation/scripts/setup-provider.sh && ./tfp-automation/scripts/setup-provider.sh rancher2 v${{ env.RANCHER2_PROVIDER_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ fromJSON(env.HB_AWS_REGION).value }}

      - name: Get AWS credentials from Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@3a411b6ec5cace3d626412dd917e7bfeac242cfa #v3
        with:
          secret-ids: |
            AWS_ACCESS_KEY, ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_KEY, ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            HB_AWS_MANAGED_PREFIX_LIST_ID_PRIME, HB_AWS_MANAGED_PREFIX_LIST_ID_PRIME
            HB_SSH_PRIVATE_KEY, HB_SSH_PRIVATE_KEY
            HB_SSH_PRIVATE_KEY_NAME, HB_SSH_PRIVATE_KEY_NAME
            HB_WINDOWS_SSH_PRIVATE_KEY, HB_WINDOWS_SSH_PRIVATE_KEY
            HB_WINDOWS_SSH_PRIVATE_KEY_NAME, HB_WINDOWS_SSH_PRIVATE_KEY_NAME
            HB_PRIVATE_FULL_CHAIN, HB_PRIVATE_FULL_CHAIN
            HB_PRIVATE_FULL_CHAIN_NAME, HB_PRIVATE_FULL_CHAIN_NAME
            HB_PRIVATE_CERT_KEY, HB_PRIVATE_CERT_KEY
            HB_PRIVATE_CERT_KEY_NAME, HB_PRIVATE_CERT_KEY_NAME
            HB_AWS_REGION, HB_AWS_REGION
            HB_TERRAFORM_VERSION, HB_TERRAFORM_VERSION
            HB_RANCHER_ADMIN_PASSWORD, HB_RANCHER_ADMIN_PASSWORD
            HB_RANCHER_VERSION_2_14_HEAD, HB_RANCHER_VERSION_2_14_HEAD
            HB_RELEASED_RANCHER_CHART_VERSION_2_14, HB_RELEASED_RANCHER_CHART_VERSION_2_14
            HB_RKE2_VERSION_2_14, HB_RKE2_VERSION_2_14
            HB_K3S_VERSION_2_14, HB_K3S_VERSION_2_14
            HB_K3S_VERSION_SUFFIX, HB_K3S_VERSION_SUFFIX
            HB_QASE_RECURRING_TEST_RUN_ID_2_14, HB_QASE_RECURRING_TEST_RUN_ID_2_14
            HB_QA_PRIVATE_REGISTRY_NAME, HB_QA_PRIVATE_REGISTRY_NAME
            HB_QASE_AUTOMATION_TOKEN, HB_QASE_AUTOMATION_TOKEN
            HB_QASE_PROJECT_ID, HB_QASE_PROJECT_ID
            HB_RANCHER_HELM_CHART_URL, HB_RANCHER_HELM_CHART_URL
            HB_SLACK_WEBHOOK_URL, HB_SLACK_WEBHOOK_URL

      - name: "Fetch and Set DockerHub Credentials"
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 #v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials username | DOCKERHUB_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials password | DOCKERHUB_PASSWORD

      - name: Mask Dockerhub Credentials
        run: |
          echo "::add-mask::${{ env.DOCKERHUB_USERNAME }}"
          echo "::add-mask::${{ env.DOCKERHUB_PASSWORD }}"

      - name: Whitelist Runner IP
        uses: ./.github/actions/whitelist-runner-ip
        with:
          prefix-list-id: ${{ fromJSON(env.HB_AWS_MANAGED_PREFIX_LIST_ID_PRIME).value }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Set up SSH Keys
        uses: ./.github/actions/setup-ssh-keys
        with:
          ssh-private-key: ${{ fromJSON(env.HB_SSH_PRIVATE_KEY).value }}
          ssh-private-key-name: ${{ fromJSON(env.HB_SSH_PRIVATE_KEY_NAME).value }}
          windows-ssh-private-key: ${{ fromJSON(env.HB_WINDOWS_SSH_PRIVATE_KEY).value }}
          windows-ssh-private-key-name: ${{ fromJSON(env.HB_WINDOWS_SSH_PRIVATE_KEY_NAME).value }}

      - name: Set up certificates
        id: setup-certs
        uses: ./.github/actions/setup-certs
        with:
          private-full-chain: ${{ fromJSON(env.HB_PRIVATE_FULL_CHAIN).value }}
          private-full-chain-name: ${{ fromJSON(env.HB_PRIVATE_FULL_CHAIN_NAME).value }}
          private-cert-key: ${{ fromJSON(env.HB_PRIVATE_CERT_KEY).value }}
          private-cert-key-name: ${{ fromJSON(env.HB_PRIVATE_CERT_KEY_NAME).value }}

      - name: Uniquify hostname prefix
        uses: ./.github/actions/uniquify-hostname

      - name: Set Rancher version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_VERSION
          value: |
            ${{
              github.event.inputs.rancher_version ||
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_version) ||
              (github.event_name == 'schedule' && vars.RANCHER_VERSION_2_14_HEAD)
            }}

      - name: Set Rancher chart version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_CHART_VERSION
          value: |
            ${{ 
              github.event.inputs.rancher_chart_version || 
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_chart_version) ||
              (github.event_name == 'schedule' && vars.RELEASED_RANCHER_CHART_VERSION_2_14)
            }}

      - name: Get Qase ID
        id: get-qase-id
        uses: ./.github/actions/get-qase-id
        with:
          qase_recurring_id: ${{ fromJSON(env.HB_QASE_RECURRING_TEST_RUN_ID_2_14).value }}

      - name: Retrieve and set ECR password
        id: get-ecr-password
        uses: ./.github/actions/get-ecr-password

      - name: Create config.yaml
        run: |
          cat > config.yaml <<EOF
          rancher:
            host: "${{ env.HOSTNAME_PREFIX }}.<HB_AWS_ROUTE_53_ZONE>"
            adminPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
            insecure: true
            cleanup: true
          terraform:
            cni: "<HB_CNI>"
            defaultClusterRoleForProjectMembers: "true"
            enableNetworkPolicy: false
            localCluster: "${{ env.LOCAL_CLUSTER_TYPE }}"
            provider: "<HB_PROVIDER_AMAZON>"
            privateKeyPath: "<HB_TFP_SSH_PRIVATE_KEY_PATH>"
            privateFullChainPath: "${{ steps.setup-certs.outputs.private-full-chain-tfp-path }}"
            privateCertKeyPath: "${{ steps.setup-certs.outputs.private-cert-key-tfp-path }}"
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            awsCredentials:
              awsAccessKey: "$AWS_ACCESS_KEY"
              awsSecretKey: "$AWS_SECRET_KEY"
            awsConfig:
              ami: "<HB_AWS_AMI>"
              awsKeyName: "<HB_SSH_PRIVATE_KEY_NAME>"
              awsInstanceType: "<HB_AWS_INSTANCE_TYPE>"
              awsVolumeType: "<HB_AWS_VOLUME_TYPE>"
              region: "<HB_AWS_REGION>"
              awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS_PRIME>]
              awsSecurityGroupNames: [<HB_AWS_SECURITY_GROUP_NAMES_PRIME>]
              awsSubnetID: "<HB_AWS_SUBNET_ID>"
              awsVpcID: "<HB_AWS_VPC_ID>"
              awsZoneLetter: "<HB_AWS_ZONE_LETTER>"
              awsRootSize: <HB_AWS_ROOT_SIZE>
              registryRootSize: <HB_AWS_ROOT_SIZE_REGISTRY>
              awsRoute53Zone: "<HB_AWS_ROUTE_53_ZONE>"
              awsUser: "<HB_AWS_USER>"
              sshConnectionType: "<HB_SSH_CONNECTION_TYPE>" 
              timeout: "<HB_TIMEOUT>"
              ipAddressType: "<HB_IP_ADDRESS_TYPE>"
              loadBalancerType: "<HB_LOAD_BALANCER_TYPE>"
              targetType: "<HB_TARGET_TYPE>"
            standalone:
              bootstrapPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
              certManagerVersion: "<HB_CERT_MANAGER_VERSION>"
              chartVersion: "${{ env.RANCHER_CHART_VERSION }}"
              k3sVersion: "<HB_K3S_VERSION_2_14><HB_K3S_VERSION_SUFFIX>"
              osUser: "<HB_OS_USER>"
              osGroup: "<HB_OS_GROUP>"
              rancherAgentImage: "<HB_RANCHER_AGENT_IMAGE>"
              rancherChartRepository: "<HB_RANCHER_HELM_CHART_URL>"
              rancherHostname: "${{ env.HOSTNAME_PREFIX }}.<HB_AWS_ROUTE_53_ZONE>"
              rancherImage: "<HB_RANCHER_IMAGE>"
              rancherTagVersion: "${{ env.RANCHER_VERSION }}"
              registryPassword: "${{ env.DOCKERHUB_PASSWORD }}"
              registryUsername: "${{ env.DOCKERHUB_USERNAME }}"
              repo: "<HB_RANCHER_REPO>"
              rke2Version: "<HB_RKE2_VERSION_2_14>"
            standaloneRegistry:
              assetsPath: "<HB_ASSETS_PATH>"
              createUnauthGlobalRegistry: true
              registryName: "${{ env.HOSTNAME_PREFIX }}"
              registryPassword: "${{ env.HOSTNAME_PREFIX }}-pass"
              registryUsername: "${{ env.HOSTNAME_PREFIX }}-user"
              ecrUsername: "<HB_ECR_USERNAME>"
              ecrPassword: "${{ steps.get-ecr-password.outputs.password }}"
              ecrURI: "<HB_ECR_URI>"
              useAuthGlobalRegistry: false
          terratest:
            pathToRepo: "<HB_PATH_TO_REPO>"
            standaloneLogging: <HB_TERRAFORM_LOGGING>

          clusterConfig:
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            cni: "<HB_CNI>"
            provider: "<HB_PROVIDER_AMAZON>"
            nodeProvider: "ec2"
            pathToRepo: "<HB_PATH_TO_TESTS_REPO>"

          logging:
            level: "<HB_LOGGING_LEVEL>"

          awsCredentials:
            secretKey: "$AWS_SECRET_KEY"
            accessKey: "$AWS_ACCESS_KEY"
            defaultRegion: "<HB_AWS_REGION>"

          awsMachineConfigs:
            region: "<HB_AWS_REGION>"
            awsMachineConfig:
            - roles: ["etcd", "controlplane", "worker"]
              ami: "<HB_AWS_AMI>"
              instanceType: "<HB_AWS_INSTANCE_TYPE>"
              sshUser: "<HB_AWS_USER>"
              vpcId: "<HB_AWS_VPC_ID>"
              subnetId: "<HB_AWS_SUBNET_ID>"
              volumeType: "<HB_AWS_VOLUME_TYPE>"
              zone: "<HB_AWS_ZONE_LETTER>"
              retries: "5"
              rootSize: "<HB_AWS_ROOT_SIZE>"
              iamInstanceProfile: "<HB_AWS_IAM_PROFILE>"

          awsEC2Configs:
            region: "<HB_AWS_REGION>"
            awsSecretAccessKey: "$AWS_SECRET_KEY"
            awsAccessKeyID: "$AWS_ACCESS_KEY"
            awsEC2Config:
              - awsRegionAZ: "<HB_AWS_REGION><HB_AWS_ZONE_LETTER>"
                awsAMI: "<HB_AWS_AMI>"
                instanceType: "<HB_AWS_INSTANCE_TYPE>"
                awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS_PRIME>]
                awsSubnetID: "<HB_AWS_SUBNET_ID>"
                awsSSHKeyName: "<HB_SSH_PRIVATE_KEY_NAME>.pem"
                awsCICDInstanceTag: "rancher-validation"
                awsIAMProfile: "<HB_AWS_IAM_PROFILE>"
                awsUser: "<HB_AWS_USER>"
                volumeSize: <HB_AWS_ROOT_SIZE>
                roles: ["etcd", "controlplane", "worker"]
              - instanceType: "<HB_AWS_WINDOWS_INSTANCE_TYPE>"
                awsRegionAZ: "<HB_AWS_REGION><HB_AWS_ZONE_LETTER>"
                awsAMI: "<HB_WINDOWS_2022_AMI>"
                awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS_PRIME>]
                awsSubnetID: "<HB_AWS_SUBNET_ID>"
                awsSSHKeyName: "<HB_WINDOWS_SSH_PRIVATE_KEY_NAME>.pem"
                awsCICDInstanceTag: "rancher-validation"
                awsUser: "<HB_AWS_WINDOWS_USER>"
                volumeSize: <HB_AWS_ROOT_SIZE>
                roles: ["windows"]
          sshPath: 
            sshPath: "<HB_SSH_PRIVATE_KEY_PATH>"
          EOF

      - name: Export CATTLE_TEST_CONFIG
        run: echo "CATTLE_TEST_CONFIG=${{ github.workspace }}/config.yaml" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go environment
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 #v6
        with:
          go-version-file: "./go.mod"

      - name: Build Packages
        run: ./.github/scripts/go-build.sh

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@c4a0df2e75a225d979a444342dd3db752b53619f

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4
        with:
          terraform_version: "${{ fromJSON(env.HB_TERRAFORM_VERSION).value }}"
          terraform_wrapper: false

      - name: Creating Rancher server
        run: go run /home/runner/work/tests/tests/validation/recurring/infrastructure/setuprancher/registry/main.go

      - name: Run Provisioning tests
        env:
          QASE_TEST_RUN_ID: ${{ steps.get-qase-id.outputs.id }}
          QASE_AUTOMATION_TOKEN: ${{ fromJSON(env.HB_QASE_AUTOMATION_TOKEN).value }}
          QASE_CUSTOM_FIELD_FILTER: Hostbusters
          QASE_SCHEMA_PREFIX: hostbusters
          QASE_PROJECT_ID: ${{ fromJSON(env.HB_QASE_PROJECT_ID).value }}
        uses: ./.github/actions/run-hostbusters-provisioning
        with:
          reporting: ${{ env.REPORTING_ENABLED }}
          tags: registries

      - name: Cleanup Infrastructure
        if: always()
        working-directory: tfp-automation/modules/registries/unauthGlobal
        run: terraform destroy -auto-approve > /dev/null 2>&1

      - name: Refresh AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Infrastructure Cleanup
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Downstream Cleanup - Node driver
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "auto-${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Downstream Cleanup - Custom
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "rancher-validation${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Revoke Runner IP
        if: always()
        uses: ./.github/actions/revoke-runner-ip
        with:
          prefix-list-id: ${{ fromJSON(env.HB_AWS_MANAGED_PREFIX_LIST_ID_PRIME).value }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Set job status output
        if: always()
        run: echo "job_status=${{ job.status }}" >> $GITHUB_OUTPUT
        id: set-job-status

      - name: Reporting Results to Slack
        if: always() && env.REPORTING_ENABLED == 'true'
        uses: ./.github/actions/report-to-slack
        with:
          rancher-version: ${{ env.RANCHER_VERSION }}
          job-status: ${{ steps.set-job-status.outputs.job_status }}
          slack-webhook-url: ${{ fromJSON(env.HB_SLACK_WEBHOOK_URL).value }}

  v2-13:
    if: |
      (github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.rancher_version, 'v2.13-head'))
    name: ${{ github.event.inputs.rancher_version }}
    runs-on: ubuntu-latest
    environment: prime-head
    env:
      HOSTNAME_PREFIX: "r213"
      RANCHER2_PROVIDER_VERSION: "${{ vars.RANCHER2_PROVIDER_VERSION_2_13 }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          submodules: recursive

      - name: Checkout tfp-automation repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          repository: rancher/tfp-automation
          path: tfp-automation

      - name: Set up local rancher2 Terraform provider
        if: contains(env.RANCHER2_PROVIDER_VERSION, '-rc')
        run: chmod +x ./tfp-automation/scripts/setup-provider.sh && ./tfp-automation/scripts/setup-provider.sh rancher2 v${{ env.RANCHER2_PROVIDER_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

            - name: Get AWS credentials from Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@3a411b6ec5cace3d626412dd917e7bfeac242cfa #v3
        with:
          secret-ids: |
            AWS_ACCESS_KEY, ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_KEY, ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            HB_AWS_MANAGED_PREFIX_LIST_ID_PRIME, HB_AWS_MANAGED_PREFIX_LIST_ID_PRIME
            HB_SSH_PRIVATE_KEY, HB_SSH_PRIVATE_KEY
            HB_SSH_PRIVATE_KEY_NAME, HB_SSH_PRIVATE_KEY_NAME
            HB_WINDOWS_SSH_PRIVATE_KEY, HB_WINDOWS_SSH_PRIVATE_KEY
            HB_WINDOWS_SSH_PRIVATE_KEY_NAME, HB_WINDOWS_SSH_PRIVATE_KEY_NAME
            HB_PRIVATE_FULL_CHAIN, HB_PRIVATE_FULL_CHAIN
            HB_PRIVATE_FULL_CHAIN_NAME, HB_PRIVATE_FULL_CHAIN_NAME
            HB_PRIVATE_CERT_KEY, HB_PRIVATE_CERT_KEY
            HB_PRIVATE_CERT_KEY_NAME, HB_PRIVATE_CERT_KEY_NAME
            HB_AWS_REGION, HB_AWS_REGION
            HB_TERRAFORM_VERSION, HB_TERRAFORM_VERSION
            HB_RANCHER_ADMIN_PASSWORD, HB_RANCHER_ADMIN_PASSWORD
            HB_RANCHER_VERSION_2_13_HEAD, HB_RANCHER_VERSION_2_13_HEAD
            HB_RELEASED_RANCHER_CHART_VERSION_2_13, HB_RELEASED_RANCHER_CHART_VERSION_2_13
            HB_RKE2_VERSION_2_13, HB_RKE2_VERSION_2_13
            HB_K3S_VERSION_2_13, HB_K3S_VERSION_2_13
            HB_K3S_VERSION_SUFFIX, HB_K3S_VERSION_SUFFIX
            HB_QASE_RECURRING_TEST_RUN_ID_2_13, HB_QASE_RECURRING_TEST_RUN_ID_2_13
            HB_QA_PRIVATE_REGISTRY_NAME, HB_QA_PRIVATE_REGISTRY_NAME
            HB_QASE_AUTOMATION_TOKEN, HB_QASE_AUTOMATION_TOKEN
            HB_QASE_PROJECT_ID, HB_QASE_PROJECT_ID
            HB_RANCHER_HELM_CHART_URL, HB_RANCHER_HELM_CHART_URL
            HB_SLACK_WEBHOOK_URL, HB_SLACK_WEBHOOK_URL

      - name: "Fetch and Set DockerHub Credentials"
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 #v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials username | DOCKERHUB_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials password | DOCKERHUB_PASSWORD

      - name: Mask Dockerhub Credentials
        run: |
          echo "::add-mask::${{ env.DOCKERHUB_USERNAME }}"
          echo "::add-mask::${{ env.DOCKERHUB_PASSWORD }}"

      - name: Whitelist Runner IP
        uses: ./.github/actions/whitelist-runner-ip
        with:
          prefix-list-id: ${{ fromJSON(env.HB_AWS_MANAGED_PREFIX_LIST_ID_PRIME).value }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Set up SSH Keys
        uses: ./.github/actions/setup-ssh-keys
        with:
          ssh-private-key: ${{ fromJSON(env.HB_SSH_PRIVATE_KEY).value }}
          ssh-private-key-name: ${{ fromJSON(env.HB_SSH_PRIVATE_KEY_NAME).value }}
          windows-ssh-private-key: ${{ fromJSON(env.HB_WINDOWS_SSH_PRIVATE_KEY).value }}
          windows-ssh-private-key-name: ${{ fromJSON(env.HB_WINDOWS_SSH_PRIVATE_KEY_NAME).value }}

      - name: Set up certificates
        id: setup-certs
        uses: ./.github/actions/setup-certs
        with:
          private-full-chain: ${{ fromJSON(env.HB_PRIVATE_FULL_CHAIN).value }}
          private-full-chain-name: ${{ fromJSON(env.HB_PRIVATE_FULL_CHAIN_NAME).value }}
          private-cert-key: ${{ fromJSON(env.HB_PRIVATE_CERT_KEY).value }}
          private-cert-key-name: ${{ fromJSON(env.HB_PRIVATE_CERT_KEY_NAME).value }}

      - name: Uniquify hostname prefix
        uses: ./.github/actions/uniquify-hostname

      - name: Set Rancher version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_VERSION
          value: |
            ${{
              github.event.inputs.rancher_version ||
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_version)
            }}

      - name: Set Rancher chart version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_CHART_VERSION
          value: |
            ${{ 
              github.event.inputs.rancher_chart_version || 
              (github.event_name == 'workflow_dispatch' && github.event.inputs.rancher_chart_version)
            }}

      - name: Get Qase ID
        id: get-qase-id
        uses: ./.github/actions/get-qase-id
        with:
          qase_recurring_id: ${{ fromJSON(env.HB_QASE_RECURRING_TEST_RUN_ID_2_13).value }}

      - name: Retrieve and set ECR password
        id: get-ecr-password
        uses: ./.github/actions/get-ecr-password

      - name: Create config.yaml
        run: |
          cat > config.yaml <<EOF
          rancher:
            host: "${{ env.HOSTNAME_PREFIX }}.<HB_AWS_ROUTE_53_ZONE>"
            adminPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
            insecure: true
            cleanup: true
          terraform:
            cni: "<HB_CNI>"
            defaultClusterRoleForProjectMembers: "true"
            enableNetworkPolicy: false
            localCluster: "${{ env.LOCAL_CLUSTER_TYPE }}"
            provider: "<HB_PROVIDER_AMAZON>"
            privateKeyPath: "<HB_TFP_SSH_PRIVATE_KEY_PATH>"
            privateFullChainPath: "${{ steps.setup-certs.outputs.private-full-chain-tfp-path }}"
            privateCertKeyPath: "${{ steps.setup-certs.outputs.private-cert-key-tfp-path }}"
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            awsCredentials:
              awsAccessKey: "$AWS_ACCESS_KEY"
              awsSecretKey: "$AWS_SECRET_KEY"
            awsConfig:
              ami: "<HB_AWS_AMI>"
              awsKeyName: "<HB_SSH_PRIVATE_KEY_NAME>"
              awsInstanceType: "<HB_AWS_INSTANCE_TYPE>"
              awsVolumeType: "<HB_AWS_VOLUME_TYPE>"
              region: "<HB_AWS_REGION>"
              awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS_PRIME>]
              awsSecurityGroupNames: [<HB_AWS_SECURITY_GROUP_NAMES_PRIME>]
              awsSubnetID: "<HB_AWS_SUBNET_ID>"
              awsVpcID: "<HB_AWS_VPC_ID>"
              awsZoneLetter: "<HB_AWS_ZONE_LETTER>"
              awsRootSize: <HB_AWS_ROOT_SIZE>
              registryRootSize: <HB_AWS_ROOT_SIZE_REGISTRY>
              awsRoute53Zone: "<HB_AWS_ROUTE_53_ZONE>"
              awsUser: "<HB_AWS_USER>"
              sshConnectionType: "<HB_SSH_CONNECTION_TYPE>" 
              timeout: "<HB_TIMEOUT>"
              ipAddressType: "<HB_IP_ADDRESS_TYPE>"
              loadBalancerType: "<HB_LOAD_BALANCER_TYPE>"
              targetType: "<HB_TARGET_TYPE>"
            standalone:
              bootstrapPassword: "<HB_RANCHER_ADMIN_PASSWORD>"
              certManagerVersion: "<HB_CERT_MANAGER_VERSION>"
              chartVersion: "${{ env.RANCHER_CHART_VERSION }}"
              k3sVersion: "<HB_K3S_VERSION_2_13><HB_K3S_VERSION_SUFFIX>"
              osUser: "<HB_OS_USER>"
              osGroup: "<HB_OS_GROUP>"
              rancherAgentImage: "<HB_RANCHER_AGENT_IMAGE>"
              rancherChartRepository: "<HB_RANCHER_HELM_CHART_URL>"
              rancherHostname: "${{ env.HOSTNAME_PREFIX }}.<HB_AWS_ROUTE_53_ZONE>"
              rancherImage: "<HB_RANCHER_IMAGE>"
              rancherTagVersion: "${{ env.RANCHER_VERSION }}"
              registryPassword: "${{ env.DOCKERHUB_PASSWORD }}"
              registryUsername: "${{ env.DOCKERHUB_USERNAME }}"
              repo: "<HB_RANCHER_REPO>"
              rke2Version: "<HB_RKE2_VERSION_2_13>"
            standaloneRegistry:
              assetsPath: "<HB_ASSETS_PATH>"
              createUnauthGlobalRegistry: true
              registryName: "${{ env.HOSTNAME_PREFIX }}"
              registryPassword: "${{ env.HOSTNAME_PREFIX }}-pass"
              registryUsername: "${{ env.HOSTNAME_PREFIX }}-user"
              ecrUsername: "<HB_ECR_USERNAME>"
              ecrPassword: "${{ steps.get-ecr-password.outputs.password }}"
              ecrURI: "<HB_ECR_URI>"
              useAuthGlobalRegistry: false
          terratest:
            pathToRepo: "<HB_PATH_TO_REPO>"
            standaloneLogging: <HB_TERRAFORM_LOGGING>

          clusterConfig:
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            cni: "<HB_CNI>"
            provider: "<HB_PROVIDER_AMAZON>"
            nodeProvider: "ec2"
            pathToRepo: "<HB_PATH_TO_TESTS_REPO>"

          logging:
            level: "<HB_LOGGING_LEVEL>"

          awsCredentials:
            secretKey: "$AWS_SECRET_KEY"
            accessKey: "$AWS_ACCESS_KEY"
            defaultRegion: "<HB_AWS_REGION>"

          awsMachineConfigs:
            region: "<HB_AWS_REGION>"
            awsMachineConfig:
            - roles: ["etcd", "controlplane", "worker"]
              ami: "<HB_AWS_AMI>"
              instanceType: "<HB_AWS_INSTANCE_TYPE>"
              sshUser: "<HB_AWS_USER>"
              vpcId: "<HB_AWS_VPC_ID>"
              subnetId: "<HB_AWS_SUBNET_ID>"
              volumeType: "<HB_AWS_VOLUME_TYPE>"
              zone: "<HB_AWS_ZONE_LETTER>"
              retries: "5"
              rootSize: "<HB_AWS_ROOT_SIZE>"
              iamInstanceProfile: "<HB_AWS_IAM_PROFILE>"

          awsEC2Configs:
            region: "<HB_AWS_REGION>"
            awsSecretAccessKey: "$AWS_SECRET_KEY"
            awsAccessKeyID: "$AWS_ACCESS_KEY"
            awsEC2Config:
              - awsRegionAZ: "<HB_AWS_REGION><HB_AWS_ZONE_LETTER>"
                awsAMI: "<HB_AWS_AMI>"
                instanceType: "<HB_AWS_INSTANCE_TYPE>"
                awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS_PRIME>]
                awsSubnetID: "<HB_AWS_SUBNET_ID>"
                awsSSHKeyName: "<HB_SSH_PRIVATE_KEY_NAME>.pem"
                awsCICDInstanceTag: "rancher-validation"
                awsIAMProfile: "<HB_AWS_IAM_PROFILE>"
                awsUser: "<HB_AWS_USER>"
                volumeSize: <HB_AWS_ROOT_SIZE>
                roles: ["etcd", "controlplane", "worker"]
              - instanceType: "<HB_AWS_WINDOWS_INSTANCE_TYPE>"
                awsRegionAZ: "<HB_AWS_REGION><HB_AWS_ZONE_LETTER>"
                awsAMI: "<HB_WINDOWS_2022_AMI>"
                awsSecurityGroups: [<HB_AWS_SECURITY_GROUPS_PRIME>]
                awsSubnetID: "<HB_AWS_SUBNET_ID>"
                awsSSHKeyName: "<HB_WINDOWS_SSH_PRIVATE_KEY_NAME>.pem"
                awsCICDInstanceTag: "rancher-validation"
                awsUser: "<HB_AWS_WINDOWS_USER>"
                volumeSize: <HB_AWS_ROOT_SIZE>
                roles: ["windows"]
          sshPath: 
            sshPath: "<HB_SSH_PRIVATE_KEY_PATH>"
          EOF

      - name: Export CATTLE_TEST_CONFIG
        run: echo "CATTLE_TEST_CONFIG=${{ github.workspace }}/config.yaml" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go environment
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 #v6
        with:
          go-version-file: "./go.mod"

      - name: Build Packages
        run: ./.github/scripts/go-build.sh

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@c4a0df2e75a225d979a444342dd3db752b53619f

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4
        with:
          terraform_version: "${{ fromJSON(env.HB_TERRAFORM_VERSION).value }}"
          terraform_wrapper: false

      - name: Creating Rancher server
        run: go run /home/runner/work/tests/tests/validation/recurring/infrastructure/setuprancher/registry/main.go

      - name: Run Provisioning tests
        env:
          QASE_TEST_RUN_ID: ${{ steps.get-qase-id.outputs.id }}
          QASE_AUTOMATION_TOKEN: ${{ fromJSON(env.HB_QASE_AUTOMATION_TOKEN).value }}
          QASE_CUSTOM_FIELD_FILTER: Hostbusters
          QASE_SCHEMA_PREFIX: hostbusters
          QASE_PROJECT_ID: ${{ fromJSON(env.HB_QASE_PROJECT_ID).value }}
        uses: ./.github/actions/run-hostbusters-provisioning
        with:
          reporting: ${{ env.REPORTING_ENABLED }}
          tags: registries

      - name: Cleanup Infrastructure
        if: always()
        working-directory: tfp-automation/modules/registries/unauthGlobal
        run: terraform destroy -auto-approve > /dev/null 2>&1

      - name: Refresh AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Infrastructure Cleanup
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Downstream Cleanup - Node driver
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "auto-${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: AWS Custodian Downstream Cleanup - Custom
        if: always()
        uses: ./.github/actions/aws-cleanup
        with:
          prefix: "rancher-validation${{ env.HOSTNAME_PREFIX }}"
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Revoke Runner IP
        if: always()
        uses: ./.github/actions/revoke-runner-ip
        with:
          prefix-list-id: ${{ fromJSON(env.HB_AWS_MANAGED_PREFIX_LIST_ID_PRIME).value }}
          region: "${{ fromJSON(env.HB_AWS_REGION).value }}"

      - name: Set job status output
        if: always()
        run: echo "job_status=${{ job.status }}" >> $GITHUB_OUTPUT
        id: set-job-status

      - name: Reporting Results to Slack
        if: always() && env.REPORTING_ENABLED == 'true'
        uses: ./.github/actions/report-to-slack
        with:
          rancher-version: ${{ env.RANCHER_VERSION }}
          job-status: ${{ steps.set-job-status.outputs.job_status }}
          slack-webhook-url: ${{ fromJSON(env.HB_SLACK_WEBHOOK_URL).value }}